config/routes.rb
Synthesis::Application.routes.draw do

  post  'activities/search'         => 'activities#search'
  get   'surprise'                  => 'activities#surprise'
  get   'activities/results'        => 'activities#results'
  resources :activities, :only => [:index, :show]
  resources :categories, :only => [:index, :show] do
    get 'about', :on => :member
  end
  resources :admin, :except => [:new, :create, :show] do
    post 'edit_multiple', :on => :collection
    put  'update_multiple', :on => :collection
  end

  post  'activities/:id/coordinates'  => 'activities#coordinates'
  post  'activities/:id/increment'    => 'activities#increment'
  post  'activities/populate'         => 'activities#populate_search'
  match 'activities/:id/:url_slug'    => 'activities#show'
  match 'categories/:id/:url_slug'    => 'categories#show'
  post  'weather'                     => 'activities#weather'
  get   'admin/scubasteve'            => 'admin#scubasteve'

  root :to => 'activities#index'

end

app/views/admin/editing.html.erb
<% if @words %>
  <%= form_for :word, :url => update_multiple_admin_index_path, :html => { :method => :put } do |f| %>
  <h2> Input to change:</h2>
    <ul>
      <% @words.each do |word| %>
        <li>
          <%= hidden_field_tag "word_ids[]", word.id %>
          <%= word.word %>
        </li>
      <% end %>
    </ul>
    <br>
    <br>
    <p>
      <%= f.label :wordable_type %><br />
      <%= f.select :wordable_type, Word.pluck(:wordable_type).uniq, {:include_blank => true } %>
    </p>
    <br>
    <br>
      <%= f.label :interpretation %><br />
      <%= f.text_field :interpretation %>
    </p>
    <br>
    <br>
    <p>
      <%= f.label "Wordable ID" %><br />
      <%= f.text_field :wordable_id %>
    </p>
    <p><%= f.submit "Submit" %></p>
  <% end %>
<% else %>
  <%= form_for :word, :url => admin_path, :html => { :method => :put } do |f| %>
  <h2> Input to change:</h2>
    <ul>
        <li>
          <%= hidden_field_tag "word_id", @word.id %>
          <%= @word.word %>
        </li>
    </ul>
    <br>
    <br>
    <p>
      <%= f.label :wordable_type %><br />
      <%= f.select :wordable_type, Word.pluck(:wordable_type).uniq, {:include_blank => true } %>
    </p>
    <br>
    <br>
      <%= f.label :interpretation %><br />
      <%= f.text_field :interpretation %>
    </p>
    <br>
    <br>
    <p>
      <%= f.label "Wordable ID" %><br />
      <%= f.text_field :wordable_id %>
    </p>
    <p><%= f.submit "Submit" %></p>
  <% end %>
<% end %>

app/views/admin/error.html.erb
<h2> Sup Bro. You looking for something? </h2>

app/views/admin/table.html.erb
<div>
  <table>
    <tr>
      <th> To Edit </th>
      <th> Word </th>
      <th> Counter </th>
      <th> Type </th>
      <th> ID </th>
      <th> Interpretation </th>
    </tr>
    <tbody>
      <%= form_tag edit_multiple_admin_index_path do %>
        <% @words.each do |word| %>
        <tr>
          <td> <%= check_box_tag "word_ids[]", word.id%> </td>
          <td> <%= word.word %></td>
          <td> <%= word.counter%></td>
          <td> <%= word.wordable_type %></td>
          <td> <%= "nil id" if word.wordable_id.nil? %></td>
          <td> <%= "nil interp" if word.interpretation.nil? %></td>
          <td> <%= link_to "Edit", edit_admin_path(word.id) %> </td>
          <td> <%= link_to "Delete", admin_path(word.id), :method => :delete %> </td>
        </tr>
        <% end %>
      <%= submit_tag "Edit" %>
      <% end %>
    </tbody>
  </table>
</div>