config/routes.rb
Synthesis::Application.routes.draw do

  post  'activities/search'         => 'activities#search'
  get   'surprise'                  => 'activities#surprise'
  get   'activities/results'        => 'activities#results'
  resources :activities, :only => [:index, :show]
  resources :categories, :only => [:index, :show] do
    get 'about', :on => :member
  end
  resources :admin, :except => [:new, :create, :show] do
    post 'edit_multiple', :on => :collection
    put  'update_multiple', :on => :collection
  end

  post  'activities/:id/coordinates'  => 'activities#coordinates'
  post  'activities/:id/increment'    => 'activities#increment'
  post  'activities/populate'         => 'activities#populate_search'
  match 'activities/:id/:url_slug'    => 'activities#show'
  match 'categories/:id/:url_slug'    => 'categories#show'
  post  'weather'                     => 'activities#weather'
  get   'admin/scubasteve'            => 'admin#scubasteve'

  root :to => 'activities#index'

end

app/models/category.rb
# encoding: utf-8

require 'slug_mapping'

class Category < ActiveRecord::Base

  validates :name, :presence => true, :uniqueness => true
  has_many :activities
  
  after_save :give_wordable
  before_create :slug_it

  attr_accessible :name, 
  :image_url, 
  :video_url, 
  :description, 
  :url_slug

  def to_param
    "#{id}/#{url_slug}"
  end


  def give_wordable
    word = Word.create(:word => self.name.downcase, :wordable_type => "category", :wordable_id => self.id, :counter => 0)
  end
  
  def self.all_sorted
    Category.order(:name).all
  end

  private

  def slug_convert (str, trim = false)
    result = ''

    str.each_char do |kar|
      if SlugMapping.include?(kar)
        result << SlugMapping[kar]
      end
    end

    if trim
      tmp = result
      result = ""
      prefix = ""
      tmp.each_char do |kar|
        if kar == '-'
          prefix = "-"
        else
          prefix = '' if result == ""
          result << prefix + kar
          prefix = ''
        end
      end
    end

    result
  end

  def slug_it
    self.url_slug = slug_convert(self.name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all_sorted
  end

  def show
    @categories = Category.all_sorted
    @category = Category.find(params[:id])
    @activities = @category.activities
  end

  def about
    @categories = Category.all_sorted
    @category = Category.find(params[:id])
  end

end

app/views/categories/_activity.html.erb
<li><%= link_to (activity.link_title), activity_path(activity) %></li>

app/views/categories/_index.html.erb
<div id="categories">
  <p>categories</p>
  <ul>
  <% @categories.each do |category| %>
    <li><%= link_to (category.name), category_path(category) %></li>
  <% end %>
  </ul>
</div>

app/views/categories/about.html.erb
<div id="cat-title">
  <h1><%= @category.name %></h1>
</div>
<h1><%= @category.name %></h1>
  <%= image_tag @category.image_url %>
<p><%= @category.description %></p>
<iframe width="560" height="315" src="<%= @category.video_url %> " frameborder="0" allowfullscreen></iframe>

app/views/categories/show.html.erb
<div id="cat-title">
  <h1><%= @category.name %></h1>
</div>
<div id="category-header">
  <% if @category.image_url %>
    <div id="category-img" style="background: url(<%= @category.image_url %>) center center no-repeat">
  </div>
  <% end %>
  <div id="cate-desc">
    <p><%= link_to ("What is " + @category.name + "?"), about_category_path %>
  </div>
</div>

<div id="list">
<%= render 'activities/activities_sorted_list', :activities => @activities %>
</div>