config/routes.rb
Synthesis::Application.routes.draw do

  post  'activities/search'         => 'activities#search'
  get   'surprise'                  => 'activities#surprise'
  get   'activities/results'        => 'activities#results'
  resources :activities, :only => [:index, :show]
  resources :categories, :only => [:index, :show] do
    get 'about', :on => :member
  end
  resources :admin, :except => [:new, :create, :show] do
    post 'edit_multiple', :on => :collection
    put  'update_multiple', :on => :collection
  end

  post  'activities/:id/coordinates'  => 'activities#coordinates'
  post  'activities/:id/increment'    => 'activities#increment'
  post  'activities/populate'         => 'activities#populate_search'
  match 'activities/:id/:url_slug'    => 'activities#show'
  match 'categories/:id/:url_slug'    => 'categories#show'
  post  'weather'                     => 'activities#weather'
  get   'admin/scubasteve'            => 'admin#scubasteve'

  root :to => 'activities#index'

end

app/models/activity.rb
# encoding: utf-8
require 'slug_mapping'

class Activity < ActiveRecord::Base

  validates :title, :presence => true
  validates :times_visited, :presence => true
  validates :dup_status, :presence => true
  # validates :phone, :format => { :with => /\d{3}-\d{3}-\d{4}( ext| x)\d*(?=\b)/,
  #   :message => "Please use a phone number of the format '123-456-7890' with an optional extension of the format ' ext1234567890' or ' x1234567890'" }
  # validates :city, :presence => true

  belongs_to :category
  belongs_to :country
  belongs_to :region

  before_create :slug_it

  before_save :valid_phone
  before_save :eliminate_ampersands
  before_save :remove_backspaces
  before_save :serialize_title_and_description
  before_save :remove_apostrophes
  
  attr_accessible :category_id,
  :user_id,
  :extern_id,
  :title,
  :description,
  :phone,
  :creator,
  :lat,
  :long,
  :starts_at,
  :ends_at,
  :duration,
  :venue_name,
  :street,
  :city,
  :region_id, 
  :zip,
  :country_id,
  :recurrence,
  :url,
  :image_url,
  :times_visited,
  :dup_status,
  :min_price,
  :max_price,
  :url_slug,
  :title_words,
  :description_words

  def remove_apostrophes
    return if self.title.is_a?(Array) || self.description.is_a?(Array)
    return if self.title.nil?
    self.title.gsub!("&#039;", "'")
    return if self.description.nil?
    self.description.gsub!("&#039;", "'")
  end

  def serialize_title_and_description
    return if self.title.is_a?(Array) || self.description.is_a?(Array)
    self.title_words = self.title.downcase if self.title
    self.description_words = self.description.downcase if self.description
  end

  def remove_backspaces
    return if self.title.is_a?(Array) || self.description.is_a?(Array)
    return if self.title.nil?
    self.title.gsub!("&nbsp;", " ")
    return if self.description.nil?
    self.description.gsub!("&nbsp;", " ")
  end

  def eliminate_ampersands
    return if self.title.is_a?(Array) || self.description.is_a?(Array)
    return if self.title.nil?
    self.title.gsub!("&amp;", "&")
    return if self.description.nil?
    self.description.gsub!("&amp; ", "")
  end

  def upcoming?
    self.starts_at >= now
  end

  def duration_formated
    if self.duration.nil? || self.duration == 0
      return nil
    else
      minutes = ((self.duration.to_f - self.duration.to_i.to_f) * 60).to_i.to_s
      time = self.duration.to_i.to_s + " h" + ( minutes == "0" ? "" : (minutes + " min"))
      duration_of_activity(time)
    end
  end

  def location_formated
    (self.street ? self.street : "") + (self.city ? (", " + self.city) : "") + (self.region ? (", " + self.region.name) : "") + (self.zip ? (", " + self.zip.to_s) : "")
  end

  def location_formated_short
    (self.city ? self.city : "") + (self.region ? (", " + self.region.code.upcase) : "") 
  end

  def cat
    self.category.name
  end

  def display_price
    case 
    when self.min_price && self.max_price && self.min_price != self.max_price
      "between $#{min_price.to_i} and $#{max_price.to_i}"
    when self.min_price && self.max_price || self.min_price
      " $#{min_price.to_i}"
    when self.max_price
      " $#{min_price.to_i}"
    else
      nil
    end
  end

  def duration_of_activity(time)
    days = self.duration.to_i / 24
    case 
    when days > 13
      "#{days / 7} weeks"
    when days > 6 
      "#{days / 7} week, #{days % 7} day" + (days % 7 > 1 ? "s" : "")
    when days > 1 
      "#{days % 7} days, #{self.duration.to_i % 24} hour" + (self.duration.to_i / 24 > 1 ? "s" : "")
    else
      time
    end
  end

  def beginning_date_formated
    self.starts_at.strftime(" %A,%B %-d %Y, at %l:%M %P") if self.starts_at
  end

  def beginning_time_formated
    self.starts_at.strftime(" at %l:%M %P") if self.starts_at
  end

  def to_param
    "#{id}/#{url_slug}"
  end

  private

  def valid_phone
    if self.phone.blank?
      return true 
    else
      temp_number = self.phone.gsub(/[^0-9]/i, '')
      return true if temp_number.length == 0
      self.phone = number_to_phone(temp_number, "-")
    end
  end

  def number_to_phone(number, delimiter)
    num = uninternationalize(number.to_s)
    num[0..2] + delimiter + num[3..5] + delimiter + num[6..9] + ( num[10..13].blank? ? "" : (":" + num[10..13])) if num.length > 10
  end

  def uninternationalize(num)
    if num[0] == 1 && (num.length == 11 || num.length == 15)
      num[1..-1]
    else
      num
    end
  end

  def days_shift(days)
    now = Time.now
    Time.at((DateTime.new(now.year, now.month, now.day + days, 0, 0, 0, 0)).to_i - now.utc_offset)
  end

  def now
    Time.now
  end

  def past?
    self.starts_at.getlocal < now
  end


  def slug_convert (str, trim = false)
    result = ''

    str.each_char do |kar|
      if SlugMapping.include?(kar)
        result << SlugMapping[kar]
      end
    end

    if trim
      tmp = result
      result = ""
      prefix = ""
      tmp.each_char do |kar|
        if kar == '-'
          prefix = "-"
        else
          prefix = '' if result == ""
          result << prefix + kar
          prefix = ''
        end
      end
    end

    result
  end

  def slug_it
    self.url_slug = slug_convert(self.title)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  caches_page :index, :show
  include ActivitiesHelper
  include PopulateSearchHelper
  include QueryHelper
  include WeatherHelper
  
  def index
    @activities = cached_front_page
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def increment
    @activity = Activity.find(params[:id])
    @activity.times_visited += 1
    @activity.save
    render json: {result: @activity.times_visited}
  end

  def populate_search
    search = params[:search]
    result = fill_form(search)
    render json: result.to_json
  end

  def search
    if params[:page]
      @page = params[:page].to_i
      @all_conditions = params[:all_conditions]
      @arguments = params[:arguments]
    else
      @page = 1
      params_check(params)
      @search = params[:search]
      @query = assemble_query(params)
    end
    @list_of_ids = []
    @activities = Activity.find(:all, :conditions => [@all_conditions, @arguments])
    @list_of_ids = @activities.map! { |activity| activity.id }
    @activities = results_to_display(@list_of_ids, @page)      
    @pages = (@list_of_ids.length - 1) / 20 + 1
    respond_to do |format|
      format.html { render :results }
      format.json { render json: {
        'action' => 'update',
        'html' => render_to_string(partial: 'results_list.html.erb', locals: { :activities => @activities, :page => @page, :pages => @pages, :all_conditions => @all_conditions, :arguments => @arguments })

        }} 
    end
  end

  def coordinates
    activity = Activity.find(params["activity_id"].to_i)
    render json: {  :lat     => activity.lat,
      :lon     => activity.long }
    end

  def weather
    api_call(params['zip'])
    render json: { :dates         => @weather[0].join(' '),
                   :maxTemp       => @weather[1].join,
                   :minTemp       => @weather[2].join,
                   :description   => @weather[3].join,
                   :imgURL        => @weather[4].join,
                   :windDirection => @weather[5].join,
                   :windSpeed     => @weather[6].join,
                   :weatherCode   => @weather[7].join }
  end

  def surprise
    session.clear
    @activities = cached_surprise.to_a.sample(30)
    render :results
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  require 'cache.rb'

  def cached_surprise
    Cache.fetch('surprise') { surprise_me.to_a }
  end

  def surprise_me
    us = Country.find_by_code("US")
    us.activities.where("starts_at < ? AND category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ? OR category_id = ?", Time.now + 691200, 2, 7, 89, 16, 20, 22, 28, 30, 32, 33, 35, 37, 42, 45, 46, 71, 92, 93, 98, 118)
  end

  def weekend_list(activities)
   activities.select {|activity| activity; weekend?(activity.starts_at, activity.ends_at)}
  end

  def today_list(activities)
   activities.select {|activity| activity; today?(activity.starts_at, activity.ends_at)}
  end

  def all_activities
    us = Country.find_by_code("US")
    us.activities.where("ends_at > ?", Time.now - 86400)
  end

  def all_activities_for_week
    Country.find_by_code!("US").activities.where("ends_at > ? AND starts_at < ?", Time.now - 86400, Time.now + 691200)
  end

  def cached_front_page
    Cache.fetch('front_pages') { all_activities_for_week.to_a }
  end

  def sort_desc(activities, limit = nil)
    activities.sort_by! {|activity| activity.times_visited}
    limit ? activities.reverse.take(limit) : activities.reverse
  end

  def sort_asc(activities, limit = nil)
    activities.sort_by! {|activity| activity.times_visited}
    limit ? activities.take(limit) : activities
  end

  def cat_array
    Category.all_sorted.map { |category| [category.name, category.id]}
  end

  def results_to_display(results_id_array, page)
    first_event_to_show = ((page-1) * 20 + 1)
    last_event_to_show = [ (page * 20), results_id_array.length - 1].min
    @to_display = []
    (first_event_to_show..last_event_to_show).each do |index|
      @to_display << Activity.find(results_id_array[index])
    end
    p @to_display
  end
end

app/views/activities/_activities_sorted_list.html.erb
  <% if sort_desc(today_list(activities), 5) != [] %>
<div class="today">
    <h1>Today</h1>
    <ul>
    <% sort_desc(today_list(activities), 5).each do |activity| %>
      <li><%= link_to activity.title, activity_path(activity) %>
      <span><%= activity.location_formated_short %>, <%= activity.beginning_time_formated %></span>
      </li>
    <% end %>
    </ul>
</div>
  <% end %>

  <% if sort_desc(weekend_list(activities), 5) != [] %>
<div class="weekend">
    <h1>This weekend</h1>
    <ul>
    <% sort_desc(weekend_list(activities), 5).each do |activity| %>
      <li>
        <%= link_to activity.title, activity_path(activity) %> 
        <span><%= activity.location_formated_short %>, <%= activity.beginning_date_formated %></span>
      </li>
    <% end %>
    </ul>
</div>
  <% end %>

<div class="top">
  <h1>Top</h1>
  <ul>
  <% sort_desc(activities, 5).each do |activity| %>
    <li>
      <%= link_to activity.title, activity_path(activity) %>
      <span><%= activity.location_formated_short %>, <%= activity.beginning_date_formated %></span>
    </li>
  <% end %>
  </ul>
</div>

app/views/activities/_activity_link.html.erb
<li><%= activity.times_visited %> <%= link_to activity.title, activity_path(activity) %></li>

app/views/activities/_how_much_search.html.erb
<div id="how-much-search">
  <p>How much?</p>
  <div class="form-hidden">
    <%= number_field_tag :min_price, nil, :placeholder => "Min Price" %>
    <%= number_field_tag :max_price, nil, :placeholder => "Min Price" %>
  </div>
</div>

app/views/activities/_results_list.html.erb
<div id="list">
  <div id="result">
    <ul>
    <% sort_desc(activities).each do |activity| %>
      <li>
      <%= link_to activity.title, activity_path(activity) %> 
      <% if !activity.location_formated_short.blank? %> 
        <span><%= activity.location_formated_short %>
          <% if !activity.beginning_date_formated.blank? %>
            , <%=activity.beginning_date_formated %></span>
          <% else %>
            </span>
          <% end %>
        <% else %>
          <% if !activity.beginning_date_formated.blank? %>
            <span><%=activity.beginning_date_formated %></span>
          <% end %>
      <% end %>
    </li>
    <% end %>
    </ul>
  </div>

<% if page %>
  <div id="pagination">
    <% if page != 1 %>
      <% if page != 2 %>
        <p><%= link_to "<< first ", activities_search_path(:page => 1, :arguments => arguments, :all_conditions => all_conditions) %></p>
      <% end %>
    <p><%= link_to "< previous ", activities_search_path(:page => page - 1, :arguments => arguments, :all_conditions => all_conditions) %></p>
    <% end %>
    <span><%= page %> / <%= pages %></span>
      <% if page != pages %>
        <p><%= link_to " next > ", activities_search_path(:page => page + 1, :arguments => arguments, :all_conditions => all_conditions) %></p>
      <% end %>
    <% if page != pages - 1 && page != pages %>
      <p><%= link_to " last >>", activities_search_path(:page => pages, :arguments => arguments, :all_conditions => all_conditions) %></p>
    <% end %>
  </div>
<% end %>

app/views/activities/_search_form.html.erb
<!-- # category, title, description, creator, lat, long, starts_at, ends_at, duration, venue_name,
# street, city, region, zip, country, min_price, max_price -->
<div id="search-form">
  <div id="search-img">
  </div>
  <div id="search-boxes">
    <%= form_tag(activities_search_path) do %>
      <%= render 'sentence_search' %>      
        <div id="search-fields">
          <%= render 'when_search' %>
          <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
          <%= render 'where_search' %>
          <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
          <%= render 'what_search' %>
          <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
          <%= render 'how_much_search' %>
      </div>
      <div id="buttons-submit">
        <%= submit_tag "Find Events" %>
        <button>Surprise Me!</button>
      </div>
    <% end %>  
  </div>
</div>

app/views/activities/_sentence_search.html.erb
<div id="sentence-search">
  <%= text_field_tag :search, nil, :placeholder => "" %>
</div>
 

app/views/activities/_weather.html.erb
<% zipcode = '94105' if zipcode.nil? %>
<% weather = api_call(zipcode.to_s) %>
<p>Forecast Dates: <%= weather[0].join(' ') %></p>
<p>Max Temperature: <%= weather[1].join %>F</p>
<p>Min Temperature: <%= weather[2].join %>F</p>
<p>Description: <%= weather[3].join %></p>
<p><img src="<%= weather[4].join %>"></p>
<p>Wind Direction: <%= weather[5].join %></p>
<p>Wind Speed: <%= weather[6].join %>mph</p>

app/views/activities/_what_search.html.erb
<div id="what-search">
  <p>What?</p>
  <div class="form-hidden">
    <%= select_tag :category, options_from_collection_for_select(Category.all, "id", "name"), :multiple => true, :size => 7 %>
  <div class="selected-categories"></div>
  </div>
</div>

app/views/activities/_when_search.html.erb
<div id="when-search">
  <p>When?</p>
  <div class="form-hidden">
    <%= text_field_tag :starts_at, nil, :placeholder => "Start Date" %>
    <%= text_field_tag :ends_at, nil, :placeholder => "End Date"  %>
  </div>
</div>

app/views/activities/_where_search.html.erb
<div id="where-search">
  <p>Where?</p>
  <div class="form-hidden">
    <%= text_field_tag :streets, nil, :placeholder => "Street" %>
    <%= text_field_tag :cities, nil, :placeholder => "City" %>
    <%= text_field_tag :regions, nil, :placeholder => "State" %>
    <%= number_field_tag :zips, nil, :placeholder => "Zip code" %>
  </div>
</div>

app/views/activities/index.html.erb
<div id="cat-title">
  <h1>Something</h1>
</div>
<div id="search-form">
  <div id="search-img">
  <div id="search-boxes">
    <%= form_tag(activities_search_path) do %>
    <%= render 'sentence_search' %>      
    <div id="search-fields">
      <div id="when-search">
        <p>When?</p>
        <div class="form-hidden">
          <%= text_field_tag :starts_at, nil, :placeholder => "Start Date" %>
          <%= text_field_tag :ends_at, nil, :placeholder => "End Date"  %>
        </div>
      </div>
      <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
      <div id="where-search">
        <p>Where?</p>
        <div class="form-hidden">
          <%= text_field_tag :streets, nil, :placeholder => "Street", :class => 'form-extra' %>
          <%= text_field_tag :cities, nil, :placeholder => "City" %>
          <%= text_field_tag :regions, nil, :placeholder => "State" %>
          <%= number_field_tag :zips, nil, :placeholder => "Zip code", :class => 'form-extra'%>
        </div>
      </div>

      <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
      <div id="what-search">
        <p>What?</p>
        <div class="form-hidden">
          <%= select_tag :category, options_from_collection_for_select(Category.all_sorted, "id", "name"), :multiple => true, :size => 7 %>
          <div class="selected-categories"></div>
        </div>
      </div>
      <div class="and-or"><span>And</span><span>/</span><span>Or</span></div>
      <div id="how-much-search">
        <p>How much?</p>
        <div class="form-hidden">
          <%= number_field_tag :min_price, nil, :placeholder => "Min Price" %>
          <%= number_field_tag :max_price, nil, :placeholder => "Max Price" %>
        </div>
      </div>
    </div>
    <div id="buttons-submit">
      <%= submit_tag "Find Events" %>
      <%= link_to 'Surprise Me!','surprise' %>
    </div>
    <% end %>  
  </div>
</div>
</div>
<div id="list">
  <%= render 'activities/activities_sorted_list', :activities => @activities %>
</div>

app/views/activities/results.html.erb
<div id="cat-title">
  <h1>some exploring</h1>
</div>

<%if @activities.length > 0%>
  <%= render 'results_list', :activities => @activities, :page => @page, :pages => @pages, :all_conditions => @all_conditions, :arguments => @arguments %>

<% else %>
  <div class="errors">
    <h3>Sorry, we couldn't find anything for you. Would you like to try a <%= link_to  "new search?", root_path %> </h3>
  </div>
<% end %>

app/views/activities/show.html.erb
<div id="show-act">

  <div id="cat-title">
    <h1><%= link_to @activity.cat, @activity.category %></h1>
  </div>
    
  <div id ="act-title">
    <h1><%= link_to @activity.title, @activity.url, :target => "_blank" %></h1>
  </div>
    <div id= "list-desc">
      <span><%= link_to "Open activity website in a new tab", @activity.url, :target => "_blank" %></span>
    <ul>
      <% if @activity.description %>
        <li>
          <h6>Description:</h6>
          <p><%= @activity.description %></p>
        </li>
      <% end %>
      <% if @activity.beginning_time_formated %>
        <li>
          <h6>Starts:</h6>
          <p><%= @activity.beginning_time_formated %></p>
        </li>
      <% else %>
        <li>Check out the activity external link for dates and times</li>
      <% end %>
      <% if @activity.duration_formated %>
        <li>
          <h6>Duration:</h6>
          <p><%= @activity.duration_formated %></p></li>
      <% end %>
      <% if @activity.display_price %>
          <li>
            <h6>Price:</h6>
            <p><%= @activity.display_price %></p>
          </li>
      <% end %>
      <li>
        <h6>Address:</h6>
        <p>
          <%= @activity.street %>
        </p>
        <p>
        <%= @activity.city %>
          <% if @activity.region %>
            <%= ", #{@activity.region.name}" %> 
          <% end %>
          <%= ", " if @activity.zip %>
          <p class='activity-zip'>
            <%= "#{@activity.zip}" if @activity.zip %></li>
          </p>

        </p>
      </li>
    </ul>
    <%= (image_tag  @activity.image_url) if @activity.image_url %>
  </div>

  <div class="widgets">
    <div class="weather-data"></div>
    <div id="map-canvas" ></div>
  </div>

  <script>
    // var directionsService;
    var lat;
    var lon;
    // var directionsDisplay;
    var map;
    // var start;
    // var end;
    function loadScript() {
      var script  = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "http://maps.googleapis.com/maps/api/js?key=AIzaSyAvISpslNjhCIoeZzvI8YIyJqWvElXLDy4&sensor=false&callback=initialize";
      document.body.appendChild(script);
      // directionsService = new google.maps.DirectionsService();
    }

    window.onload = loadScript;
    var id = window.location.pathname.split('/')[2];
    
    $.ajax({
      type: 'post',
      url: 'coordinates',
      dataType: 'json',
      async: false,
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $  ('meta[name="csrf-token"]').attr('content'))},
      data: {activity_id: id }
    }).done(function(data){
      lat = data.lat;
      lon = data.lon;
    });
    
    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();
      google.maps.visualRefresh = true;
      var mapOptions = {
        zoom: 12,
        center: new google.maps.LatLng(lat, lon),
        mapTypeControlOptions: {
          mapTypeIds: google.maps.MapTypeId.ROADMAP
        }
      };
      map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
      TestMarker();
      // directionsDisplay.setMap(map);
    }
    
    function addMarker(location) {
      marker = new google.maps.Marker({
        position: location,
        map: map
      });
    }

    // function calcRoute() {
    //   // See link for help displaying directions: https://developers.google.com/maps/documentation/javascript/directions
    //   debugger
    //   start = new google.maps.LatLng(37.792210 , -122.406141);
    //   end = new google.maps.LatLng(lat, lon);
    //   request = {
    //     origin: start,
    //     destination: end,
    //     travelMode: google.maps.TravelMode.DRIVING
    //   };
    //   directionsService.route(request, function(result, status){
    //     if (status == google.maps.DirectionsStatus.OK) {
    //       directionsDisplay.setDirections(result);
    //     }
    //   });
    // }
    
    function TestMarker() {
      CentralPark = new google.maps.LatLng(lat, lon);
      addMarker(CentralPark);
    }

    $.ajax({
      type: 'post',
      url: 'increment',
      dataType: 'json',
    });
  </script>
</div>